### ISSUE TITLE
design the layout for the wallet site

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/BankWallet-www#1]
The site is located at http://bankwallet.app

The site will consist of a single page (+translations for that page). Attaching the image below for your reference.

**Comment by esengulov** [comment]
![222](https://user-images.githubusercontent.com/8611762/51597578-c58b4300-1f25-11e9-9333-9dbab1af8c23.jpg)

**Comment by TalgatNurdinov** [comment]
https://zpl.io/am93036

**Comment by Dianaaiym** [comment]
Last update: https://zpl.io/am93036

**Comment by TalgatNurdinov** [comment]
[iphoneX-3screens.zip](https://github.com/horizontalsystems/BankWallet-www/files/2874198/iphoneX-3screens.zip)
