### ISSUE TITLE
Header section is a bit too wide

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/BankWallet-www#14]
Header height changes
- [ ] Add fixed tab bar pinned to top on scroll 
https://zpl.io/am93036

Mobile version fixes
- [ ] Text should be center alignment and with paddings around
- [ ] Add paddings to stores badges 

![2019-03-14 12 43 22](https://user-images.githubusercontent.com/42367908/54336622-c2bfeb00-4656-11e9-94fb-1a21cf153ab0.jpg)

**Comment by esengulov** [comment]
This issues was dropped from the list due to the rebranding of the wallet website as can be seen in other project issues
